import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../../context/AuthContext';
import api from '../../../lib/axios';
import { Save, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const BrandForm = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const { token } = useAuth();
    const isEdit = !!id;

    const [formData, setFormData] = useState({
        name: '',
        slug: '',
        logo: null as File | null
    });
    const [logoPreview, setLogoPreview] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    useEffect(() => {
        if (isEdit) {
            fetchBrand();
        }
    }, [id]);

    const fetchBrand = async () => {
        try {
            const response = await api.get(`/brands/${id}/`);
            const { name, slug, logo } = response.data;
            setFormData(prev => ({ ...prev, name, slug: slug || '' })); // Ensure slug is handled if API returns it
            if (logo) setLogoPreview(logo);
        } catch (err) {
            console.error("Failed to fetch brand", err);
            setError("Failed to load brand data.");
        }
    };

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value, files } = e.target;
        if (name === 'logo' && files && files[0]) {
            setFormData(prev => ({ ...prev, logo: files[0] }));
            setLogoPreview(URL.createObjectURL(files[0]));
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        const data = new FormData();
        data.append('name', formData.name);
        // data.append('slug', formData.slug); // Usually generated by backend, but can be sent if needed
        if (formData.logo) {
            data.append('logo', formData.logo);
        }

        try {
            if (isEdit) {
                await api.patch(`/brands/${id}/`, data, {
                    headers: {
                        'Authorization': `Token ${token}`,
                        'Content-Type': 'multipart/form-data'
                    }
                });
            } else {
                await api.post('/brands/', data, {
                    headers: {
                        'Authorization': `Token ${token}`,
                        'Content-Type': 'multipart/form-data'
                    }
                });
            }
            navigate('/admin/brands');
        } catch (err) {
            console.error("Failed to save brand", err);
            setError("Failed to save brand. Please update the name and try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto">
            <div className="flex items-center gap-4 mb-8">
                <Link to="/admin/brands" className="text-[#AAAAAA] hover:text-white transition-colors">
                    <ArrowLeft className="w-6 h-6" />
                </Link>
                <h1 className="text-3xl font-bold text-white uppercase tracking-tighter font-display">
                    {isEdit ? 'Edit Brand' : 'Add New Brand'}
                </h1>
            </div>

            {error && (
                <div className="bg-[#C41E3A]/10 border border-[#C41E3A] text-[#C41E3A] p-4 mb-6 font-bold uppercase text-sm">
                    {error}
                </div>
            )}

            <form onSubmit={handleSubmit} className="bg-[#1A1A1A] border border-[#333] p-8 space-y-6">
                <div>
                    <label className="block text-[#AAAAAA] text-xs font-bold uppercase tracking-wider mb-2">Brand Name</label>
                    <input
                        type="text"
                        name="name"
                        value={formData.name}
                        onChange={handleChange}
                        className="w-full bg-[#121212] border border-[#333] text-white p-3 focus:outline-none focus:border-[#C41E3A] transition-colors"
                        required
                    />
                </div>

                <div>
                    <label className="block text-[#AAAAAA] text-xs font-bold uppercase tracking-wider mb-2">Logo Upload</label>
                    <div className="border-2 border-dashed border-[#333] p-8 text-center bg-[#121212] hover:border-[#C41E3A] transition-colors relative">
                        <input
                            type="file"
                            name="logo"
                            onChange={handleChange}
                            accept="image/*"
                            className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
                        />
                        {logoPreview ? (
                            <div className="flex flex-col items-center">
                                <img src={logoPreview} alt="Preview" className="h-20 object-contain mb-2" />
                                <span className="text-[#C41E3A] text-xs font-bold uppercase">Click to Change</span>
                            </div>
                        ) : (
                            <div className="text-[#666] text-sm">
                                <span className="text-[#C41E3A] font-bold">Click to Upload</span> or drag and drop
                            </div>
                        )}
                    </div>
                </div>

                <div className="pt-4 border-t border-[#333]">
                    <button
                        type="submit"
                        disabled={loading}
                        className="bg-[#C41E3A] hover:bg-[#A01A2E] text-white font-bold py-3 px-8 uppercase tracking-widest transition-colors flex items-center gap-2"
                    >
                        {loading ? 'Saving...' : (
                            <>
                                <Save className="w-5 h-5" /> Save Brand
                            </>
                        )}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default BrandForm;
